POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld2d1eSIsImlkIjoiNjI4Y2M0ZDFhZGFhYmYwOGU3NzFkMjU1IiwiaWF0IjoxNjUzMzkyODc0LCJleHAiOjE2NTMzOTY0NzR9.hAec_GRL-JTkXSSxNZeSQKaHsVFkXb42s8osv91NLAU

{
  "title": "blog for new guy",
  "author": "mr investor",
  "url": "http://investmentblog.org",
  "likes": 2
}